@startuml

class DeformationModel 
{
    modelIdentifier: characterString
    sourceCrs: CrsDefinition
    targetCrs: CrsDefinition
    interpolationCrs: CrsDefinition
    spatialExtent: SpatialExtent
    temporalExtent: TemporalExtent
    horizontalDisplacementUnits: UnitType[0..1]
    horizontalUncertaintyMeasure: UncertaintyMeasure[0..1]
    defaultHorizontalUncertainty: real[0..]
    verticalDisplacementUnits: UnitType[0..1]
    verticalUncertaintyMeasure: UncertaintyMeasure[0..1]
    defaultVerticalUncertainty: real
    elements: DeformationModelElement[]
}
DeformationModel "1" o-- "many" DeformationElement

note right of DeformationModel::horizontalDisplacementUnits
    Horizontal and vertical displacement units and 
    uncertainty definition are required if the 
    deformation model defines the corresponding
    displacement or uncertainty
end note

class DeformationElement
{
    spatialModel: SpatialModel
    timeFunction: TimeFunction
}
DeformationElement o-- SpatialModel
DeformationElement o-- TimeFunction

class SpatialModel
{
    gridParameters: characterString[]
    interpolationMethod: characterString
    gridTransformation: real[]
    defaultHorizontalUncertainty: real[0..1]
    defaultVerticalUncertainty: real[0..1]
    grids: Grid[]
}

note right of SpatialModel::gridParameters
    Defines which displacement and uncertainty parameters
     are defined by the spatial model.  Each grid must 
    define this set of parameters at each node.
end note

class Grid
{
    iNodeMaximum: integer
    jNodeMaximum: integer
    gridTransformation: Transformation
    noDataValue: real[0..1]
    gridData: real[][][]
    childGrids: Grid[0..]
}
SpatialModel "1" *-- "many" Grid
Grid "0" *-- "many" Grid : child

@enduml 
