@startuml

class GGXF_File 
{
    ggxfVersion: characterString
    fileName: characterString
    content: characterString
    sourceCrs: characterString
    targetCrs: characterString
    interpolationCrs: characterString
    operationAccuracy (optional): real
    uncertaintyMeasure (optional): GGXF_UncertaintyMeasure
    startDate (optional): dateTime
    endDate (optional): dateTime

}
GGXF_File "1" o-- "many" GGXF_Group
GGXF_File "1" o-- "1" GGXF_DiscoveryMetadata
GGXF_File "1" *-- "0/1" GGXF_UncertaintyMeasure


class GGXF_FileDeformation
{
    deformationApplicationMethod: characterString
    deformationBursaWolfTransformation (optional): GGXF_BursaWolfTransformation
}
GGXF_File <|-- GGXF_FileDeformation
GGXF_FileDeformation "1" *-- "0/1" GGXF_BursaWolfTransformation

class GGXF_BursaWolfTransformation
{
    transformationReferenceDate: dateTime
    transformationParameters: real[14]
}

class GGXF_DiscoveryMetadata
{
    version: characterString
    publicationDate: dateTime
    remark (optional): characterString    
    contentApplicabilityExtent: GGXF_SpatialExtent
    licence: characterString
    authority: GGXF_Contact
}
GGXF_DiscoveryMetadata "1" *-- "1" GGXF_Contact

class GGXF_Contact
{
    partyName (optional): characterString
    deliveryPoint (optional): characterString
    city (optional): characterString
    postalCode (optional): characterString
    electronicMailAddress (optional): characterString
    onlineResource (optional): characterString
}

class GGXF_UncertaintyMeasure
{
    horizontal (optional): GGXF_UncertaintyComponent
    vertical (optional): GGXF_UncertaintyComponent
}
GGXF_UncertaintyMeasure "1" *--  "many" GGXF_UncertaintyComponent

class GGXF_UncertaintyComponent
{
    name: characterString
    id: characterString
}

class GGXF_Group
{
    groupName: characterString
    remark (optional): characterString
    parameters: GGXF_Parameter[]
    interpolationMethod: characterString
    interpolationMethodCitation (optional): characterString
    grids: GGXF_Grid[]
}

class GGXF_Parameter
{
    parameterName: characterString
    unit: characterString
    unitSiRatio: real
    parameterMinimumValue (optional): real
    parameterMaximumValue (optional): real
}
GGXF_Group "1" *-- "many" GGXF_Parameter

class GGXF_GroupDeformation
{
    defaultHorizontalUncertainty (optional): real
    defaultVerticalUncertainty (optional): real
    timeFunction: GGXF_TimeFunction[]
}

GGXF_Group <|-- GGXF_GroupDeformation

class GGXF_Grid
{
    gridName: characterString
    parentGridName: characterString
    hierarchyRank: integer 
    iNodeMaximum: integer
    jNodeMaximum: integer
    affineCoeffs: real[]
    noDataFlag (optional): real
    gridData: real[][][]
}
GGXF_Group "1" *-- "many" GGXF_Grid
GGXF_Grid *-- GGXF_Grid : parent

class GGXF_SpatialExtent
{
    extentDescription (optional): characterString
    boundingBox: GGXF_BoundingBox
    extentPolygon (optional): characterString?
}
GGXF_DiscoveryMetadata "1" *-- "1" GGXF_SpatialExtent

class GGXF_BoundingBox
{
    southBoundLatitude: real
    westBoundLongitude: real
    northBoundLatitude: real
    eastBoundLongitude: real
}
GGXF_SpatialExtent "1" *-- "1" GGXF_BoundingBox

abstract class GGXF_TimeFunction
{
    type: characterString
}
GGXF_GroupDeformation "1" *-- "many" GGXF_TimeFunction

class GGXF_VelocityTimeFunction
{
    functionReferenceDate: dateTime
    functionMultiplier (optional): real
    startDate (optional): dateTime
    endDate (optional): dateTime
}
GGXF_TimeFunction <|-- GGXF_VelocityTimeFunction

class GGXF_StepTimeFunction
{
    stepDate: dateTime
    functionMultiplier (optional): real
}
GGXF_TimeFunction <|-- GGXF_StepTimeFunction

class GGXF_ReverseStepTimeFunction
{
    stepDate: dateTime
    functionMultiplier (optional): real
}
GGXF_TimeFunction <|-- GGXF_ReverseStepTimeFunction


class GGXF_PiecewiseLinearTimeFunction
{
    startDate: dateTime
    startScaleFactor: real
    endDate: dateTime
    endScaleFactor: real
}
GGXF_TimeFunction <|-- GGXF_PiecewiseLinearTimeFunction

class GGXF_ExponentialTimeFunction
{
    startDate: dateTime
    functionMultiplier: real
    decayRate: real
    endDate (optional): dateTime
}
GGXF_TimeFunction <|-- GGXF_ExponentialTimeFunction

class GGXF_LogarithmicTimeFunction
{
    startDate: dateTime
    functionMultiplier: real
    timeConstant: real
    endDate (optional): dateTime
}
GGXF_TimeFunction <|-- GGXF_LogarithmicTimeFunction

class GGXF_AccelerationTimeFunction
{
    functionReferenceDate: dateTime
    functionMultiplier: real
    startDate (optional): dateTime
    endDate (optional): dateTime
}

GGXF_TimeFunction <|-- GGXF_AccelerationTimeFunction

class GGXF_HyperbolicTangentTimeFunction
{
    startDate: dateTime
    endDate: dateTime
    functionMultiplier (optional): real
    timeConstant: real
}

GGXF_TimeFunction <|-- GGXF_HyperbolicTangentTimeFunction

class GGXF_CyclicTimeFunction
{
    functionReferenceDate: dateTime
    frequencyPerYear: integer?
    cosineMultiplier: real
    sineMultiplier: real
}
GGXF_TimeFunction <|-- GGXF_CyclicTimeFunction


@enduml 
