////

.Preface


[NOTE]
====
Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.

There are two ways to specify the Preface: "simple clause" or "full clasuse"

If the Preface does not contain subclauses, it is considered a simple preface clause. This one is entered as text after the `.Preface` label and must be placed between the AsciiDoc document attributes and the first AsciiDoc section title. It should not be give a section title of its own.

If the Preface contains subclauses, it needs to be encoded as a full preface clause. This one is recognized as a full Metanorma AsciiDoc section with te title "Preface", i.e. `== Preface`. (Simple preface content can also be encoded like full preface.)
====

////

[.preface]
== Preface

This OGC Abstract Specification has been developed by the OGC Coordinate Reference System (CRS) domain working group (DWG) in conjunction with the CRS DWG project team developing the "Gridded Geodetic Exchange Format (GGXF)" and with the International Association of Geodesy (IAG) Working group 1.3.1 on "Time-dependent transformations between reference frames in deforming regions".


[abstract]
== Abstract

This OGC Abstract Specification (AS) defines a general parameterization of deformation models. 

All objects on the surface of the earth are moving. Apparently fixed features such as buildings are moving with the earth's crust, being subject to ongoing plate tectonic movement and episodic deformation events such as earthquakes. Increasingly, applications and users rely on Global Navigation Satellite Systems (GNSS) toprecisely determine the coordinates of features.  The resulting coordinates are then stored in databases and used in a wide range of applications, such as Geographic Information Systems (GIS). However, the coordinates from GNSS are referenced to global reference frames and coordinate reference systems (CRSs).  In these reference frames ubiquitous movement of fixed objects means that the observed coordinates of these features are continually changing. 

This creates a challenge for the geospatial and positioning community: How to account for this movement when comparing data sets observed at different times, or how to locate an object observed in the past.

One solution to this challenge is to use a deformation model - a mathematical model of the deformation of the crust. This solution allows the coordinates of a fixed object to be propagated to different times so that the object's location can be tracked.

Common uses  of a deformation model include:

* Determining the current location of an object based on historic measurement of its location, 
* Propogation of the current observed location of an object to the reference epoch of a static CRS,
* Determining the spatial relationship of data sets observed at different times,
* Predicting the location of an object at some future time.

Currently, many national geodetic agencies constructed or are planning for deformation models. However, these current models generally use customized formats and are typically only used in software developed by the agency.

This AS defines a framework for describing a deformation model. This framework is called a functional model.  The model describes a way of parameterizing deformation such that it can be encoded into a data set and incorporated into software for use in coordinate operations. The model also defines how to calculate the displacement of a point between two different epochs.
This AS enables producers of deformation models, such as national geodetic agencies, to publish these models in a consistent way. Users of software that performs coordinate operations can be confident that the model is being applied as intended by the producers.

[.preface]
== Submitters

[%unnumbered]
.List of submitters
|===
h| Submitter h| Affiliation
| Wan Anom Wan Aris | UTM-GnG, Universiti Teknologi Malaysia
| Maciej Bazanowski | Geographic Information Services, Department of Service Nova Scotia and Internal Services
| Elmar Brockman | Swiss Federal Office of Topography
| Dana Caccamise | NOAA
| Michael Craymer | Canadian Geodetic Survey, Natural Resources Canada
| Chris Crook | Land Information New Zealand
| Muzaffer Kahveci | Konya Technical University
| Kevin M. Kelly | Esri
| Thomas Knudsen | The Danish Agency for Data Supply and Efficiency
| Roger Lott | IOGP
| José Antonio Tarrío Mosquera | University of Santiago de Chile
| Chris Pearson   | Trimble Inc
| Craig Roberts | University of New South Wales
| Keith Ryden | Esri
| Richard Stanaway | University of New South Wales
|===


[.preface]
== Introduction

This OGC Abstract Specification (AS) defines a general parameterization of deformation models (illustrated in <<image_structure>>).  The total deformation is decomposed into a set of elements, each of which is defined by a spatial function and a time function.  The spatial function defines the displacement that applies at a given location, and the time function defines a scalar function that applies for the element at a given time.  The displacement due to the element is the spatial function displacement multiplied by the time function scale factor.  The total displacement at the location and time is the sum of the displacements from each element.  This model is described in detail in <<section-model-definition>>.

Commonly, elements represent the effects of geophysical events, such as coseismic deformation due to an earthquake. However, an element could equally represent some measured displacement for which no physical cause has been ascribed. Also, several elements may represent different aspects of a single geophysical event.  For example, the horizontal deformation due to an earthquake may be represented by one element, and the vertical deformation by another.

Other types of deformation model not encompassed by this AS include:

* Rigid body transformation between reference frames such as time dependent Helmert or Bursa-Wolf transformations, 
* Trajectory models for individual points, such as ITRF reference station coordinate models, 
* Static distortion models used to represent the difference between two datums,
* Global plate tectonic models,
* Three dimensional geophysical models of deformation in terms of dislocations on fault surfaces such as elastic half space or finite element models. 

This AS specifies a set of parameters and metadata that define the deformation model, and how they are used to apply that model in coordinate operations.  The AS does not prescribe how they should be encoded into a digital file.  

The intention of this AS is to enable deformation model producers, such as national geodetic agencies, to publish models, and consumers to use them, with confidence that the model is being correctly interpreted and used.  

////
[.preface]
== Reference notes

<Place reference notes here.>


[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====
////
