////

.Preface

<Insert Preface text here.>


[NOTE]
====
Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.

There are two ways to specify the Preface: "simple clause" or "full clasuse"

If the Preface does not contain subclauses, it is considered a simple preface clause. This one is entered as text after the `.Preface` label and must be placed between the AsciiDoc document attributes and the first AsciiDoc section title. It should not be give a section title of its own.

If the Preface contains subclauses, it needs to be encoded as a full preface clause. This one is recognized as a full Metanorma AsciiDoc section with te title "Preface", i.e. `== Preface`. (Simple preface content can also be encoded like full preface.) 
====

////

[abstract]
== Abstract

All objects on the surface of the earth are moving.  Intuitively fixed features such buildings are moving with the earth's crust - subject to ongoing plate tectonic movement and episodic deformation events such as earthquakes.  This creates a challenge of the geospatial community.  Increasily we rely on Global Navigation Satellite Systems (GNSS) which can precisely determine the coordinates of features - coordinates we then store in Geographic Information Systems (GIS).  However the coordinates from GNSS are reference to global coordinate systems and in this reference frame the ongoing movement of these fixed objects means that the coordinates of these features are continually changing over time.

This creates a challenge for the geospatial and positioning community - how to account for this movement when comparing data sets observed at different times, or how to relocate an object located in the past.

One solution to this challenge is to use a deformation model - a mathematical model of the deformation of the crust.  It allows a "fixed" object's location to be propogated to different times. 

Common uses for this include:

* determining the current location of an object based a historic measurement of its location,
* transformation the current observed location of an object to the reference epoch of a static coordinate system
* determining the correct spatial relationship of data sets observed at different times.

Currently many national geodetic agencies construct deformation models.  However 

This specification defines a functional model for describing a deformation model.  It describes a way of parameterising deformation such that it can be encoded into a data set and incorporated into software for using in coordinate transformations.  It also defines how to calculate the displacement of a coordinate between two different times using this parameterisation.  

This specification allows producers of deformation models, typically national geodetic agencies, to publish the deformation model in a consistent way such that users of coordinate transformation software can be confident that the deformation model is being applied as intended by the producers.

[.preface]
== Submitters

[%unnumbered]
|===
h| Submitter h| Affiliation
| Chris Crook | Land Information New Zealand
| Kevin Kelly | ESRI 
| ...   | ...
|===


[.preface]
== Introduction

This specification has been developed by the OGC Coordinate Reference System (CRS) domain working group (DWG) in conjunction with the  the CRS DWG project team developing the "Gridded Geodetic Exchange Format (GGXF)" and with the International Association of Geodesy (IAG)) Working group 1.3.1 on "Time-dependent transformations between reference frames in deforming regions".

It defines a general parameterisation of deformation models for use in coordinate transformation operations.  The primary use case for this parameterisation for geodetic agencies to encode regional deformation models for use in spatial data operations in geographic information systems and in positioning systems.  

This specification does not encompass other types of deformation model such as:

* Rigid body transformation between reference frames such as time dependent helmert or Bursa-Wolf transformations,
* Trajectory models for individual points, such as ITRF reference station coordinate models,
* Static distortion models used to represent the deformation between two datums (typically between older datums based on local terrestrial observations and modern datums based on global satellite systems.)
* Global plate tectonic models, as these use a very different parameterisation of the relative movements of points
* The format for encoding the parameters and metadata of a deformation model
* Three dimensional geophysical models of deformation in terms of dislocations on fault surfaces or using finite element model

////
[.preface]
== Reference notes

<Place reference notes here.>


[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====
////
