////

.Preface


[NOTE]
====
Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.

There are two ways to specify the Preface: "simple clause" or "full clasuse"

If the Preface does not contain subclauses, it is considered a simple preface clause. This one is entered as text after the `.Preface` label and must be placed between the AsciiDoc document attributes and the first AsciiDoc section title. It should not be give a section title of its own.

If the Preface contains subclauses, it needs to be encoded as a full preface clause. This one is recognized as a full Metanorma AsciiDoc section with te title "Preface", i.e. `== Preface`. (Simple preface content can also be encoded like full preface.)
====

////

[.preface]
== Preface

This OGC Abstract Specification has been developed by the OGC Coordinate Reference System (CRS) domain working group (DWG) in conjunction with the CRS DWG project team developing the "Gridded Geodetic Exchange Format (GGXF)" and with the International Association of Geodesy (IAG) Working group 1.3.1 on "Time-dependent transformations between reference frames in deforming regions."


[abstract]
== Abstract

This OGC Abstract Specification (AS) defines a general parameterization of surface deformation models. 

All objects on the surface of the Earth are moving. Apparently fixed features such as buildings are moving with the Earth's crust, being subject to ongoing plate tectonic movement and episodic deformation events such as earthquakes. 

Increasingly, applications and users rely on global positioning methods, such as Global Navigation Satellite Systems (GNSS) observations, to precisely determine the coordinates of features.  The resulting coordinates are then stored in databases and used in a wide range of applications, such as Geographic Information Systems (GIS). However, the coordinates from GNSS are referenced to global reference frames and coordinate reference systems (CRSs).  In these reference frames the coordinates of apparently fixed objects are continually changing. 

This creates a challenge for the geospatial and positioning community: How to account for this movement when comparing data sets observed at different times, or how to locate an object observed in the past.

This problem is generally addressed in one of two ways:

* Defining a reference epoch for the CRS of coordinates held in the GIS, often by defining a CRS with a reference epoch, or
* Using a CRS which is fixed relative to the surface of the Earth.

In practice there is little difference between these two approaches.  Neither the position at a reference epoch, nor the coordinates in a static CRS, can be directly measured by global positioning methods.  

Propagating the observed coordinates to a reference epoch, or transforming to a static CRS, requires a deformation model - a mathematical model of the deformation of the Earth's surface.

Common uses of a deformation model include:

* Determining the current location of an object based on historic measurement of its location, 
* Propagation of the current observed location of an object to the reference epoch of a static CRS,
* Determining the spatial relationship of data sets observed at different times, and
* Predicting the location of an object at some future time.

Currently, many national geodetic agencies have developed or are planning to develop regional deformation models. However, the current models generally use customized formats and software developed by each agency.

This AS describes a way of parameterizing a deformation model such that it can be encoded into a data set and used in software for coordinate operations. The AS defines how to calculate the displacement of a point between two different epochs.  It provides a common understanding between producers of deformation models and developers of software about what the deformation is and how it will be used.

This AS will allow users of compliant software applying a compliant deformation model to be confident that the model is being used as intended by its producers.

[.preface]
== Submitters

[%unnumbered]
.List of submitters
|===
h| Submitter h| Affiliation
| Wan Anom Wan Aris | UTM-GnG, Universiti Teknologi Malaysia
| Maciej Bazanowski | Geographic Information Services, Department of Service Nova Scotia and Internal Services
| Elmar Brockman | Swiss Federal Office of Topography
| Dana Caccamise | NOAA
| Michael Craymer | Canadian Geodetic Survey, Natural Resources Canada
| Chris Crook | Land Information New Zealand
| Muzaffer Kahveci | Konya Technical University
| Kevin M. Kelly | Esri
| Thomas Knudsen | The Danish Agency for Data Supply and Efficiency
| Roger Lott | IOGP
| José Antonio Tarrío Mosquera | University of Santiago de Chile
| Chris Pearson   | Trimble Inc
| Craig Roberts | University of New South Wales
| Keith Ryden | Esri
| Richard Stanaway | University of New South Wales
|===


[.preface]
== Introduction

This OGC Abstract Specification (AS) defines a general parameterization of deformation models (illustrated in <<image_structure>>).  The total deformation is decomposed into a set of elements, each of which is defined by a spatial function and a time function.  The spatial function defines the displacement that applies at a given location, and the time function defines a scalar function that applies for the element at a given time.  The displacement due to the element is the spatial function displacement multiplied by the time function scale factor.  The total displacement at the location and time is the sum of the displacements from each element.  This model is described in detail in <<section-model-definition>>.

Commonly, elements represent the effects of geophysical events, such as coseismic deformation due to an earthquake. However, an element could equally represent some measured displacement for which no physical cause has been ascribed. Also, several elements may represent different aspects of a single geophysical event.  For example, the horizontal deformation due to an earthquake may be represented by one element, and the vertical deformation by another.

Other types of deformation model not encompassed by this AS include:

* Rigid body transformation between reference frames such as time dependent Helmert or Bursa-Wolf transformations, 
* Trajectory models for individual points, such as ITRF reference station coordinate models, 
* Static distortion models used to represent the difference between two datums,
* Global plate tectonic models, and
* Three dimensional geophysical models of deformation in terms of dislocations on fault surfaces such as elastic half space or finite element models. 

Although these models are not explicitly supported by this AS, the surface deformation that they predict can be represented using the parameterization specified in this AS.

This AS specifies a set of parameters and metadata that define the deformation model, and how they are used to apply that model in coordinate operations.  The AS does not prescribe how they should be encoded into a digital file.  

The intention of this AS is to enable deformation model producers, such as national geodetic agencies, to publish models, and consumers to use them, with confidence that the model is being correctly interpreted and used.  

////
[.preface]
== Reference notes

<Place reference notes here.>


[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====
////
