
== Scope

This abstract specification defines a functional model that is used to define deformation models - models of the ongoing deformation of the earth's crust - to support their implementation into coordinate operations and transformations.

Within this context a deformation model is defined as follows:
____
A deformation model is a model of the displacement of the earth’s surface within a defined spatial and temporal extent.  It predicts the location of a point fixed to the surface at any time within the temporal extent in terms of an accessible coordinate system.  The location of the point is represented as a displacement from a reference position for that point.
____

In the most abstract sense a deformation model is a mathematical function of a two dimensional coordinate and a time that defines a one, two, or three dimensional coordinate displacement.  It may also express the uncertainty of the displacement.

This specification describes a means of representing a deformation model using a set of parameters and gridded data that defines this mathematical function.  It specifies how the displacement is calculated from this data and how it is applied to a coordinate to apply the coordinate operation that the deformation model defines.  It also specifies metadata attributes that should accompany the encoded model to allow users to understand its applicability and limitations.
