
== Terms and Definitions

////
TODO: Add missing terms 

Comments from OGC editor:

Should probably reference OGC Abstract Specification Topic 2: Referencing by coordinates (ISO 19111:2019) as a dependency for CRS related T&Ds


////

////  
To be added

* coseismic (editor)
* slow slip event (author)
* displacement (pr)
* deformation (editor)
geographic CRS (editor)
carrier - plus question on the use of the verb "carry" (public review)
grid reference coordinates, grid spacing (public review)

* coordinate operation (author) (?specify PMM and transformation)
//// 

=== Terms

==== carrier

specific format used to encode a deformation model

NOTE: The carrier defines how the attributes of the deformation model are encoded. 

==== coordinate operation

process using a mathematical model, based on a one-to-one relationship, that changes coordinates in
a source coordinate reference system to coordinates in a target coordinate reference system, or that
changes coordinates at a source coordinate epoch to coordinates at a target coordinate epoch within
the same coordinate reference system

[.source]
<<ISO19111,clause 3.1.8>>

==== coseismic deformation

deformation caused by an earthquake and occurring within minutes of the earthquake

==== deformation

change in shape of the earth's crust due to stress changes within crust

NOTE: This specification is specifically concerned with the manifestion of deformation on the surface of the earth and the consequent displacement of features fixed to the surface of the earth.

==== displacement

change in the coordinates of a point due to deformation

==== geographic coordinate reference system

coordinate reference system that has a geodetic reference frame and an ellipsoidal coordinate system

[.source]
<<ISO19111,clause 3.1.35>>

==== implementation

software that uses an encoded deformation model to calculate displacements or to apply displacements in coordinate operations

NOTE:  The implementation encodes the formulae defined in this specification or numerically equivalent formulae.

==== post-seismic deformation

deformation over months or years following an earthquake due to the ongoing change in the stresses in the earth's crust following an earthquake or series of earthquakes

==== slow slip event

release of stress in the earth's crust due to gradual slipping fault surfaces over a period of months or years - a slow earthquake

==== producer

agency compiling a deformation model for publication


=== Abbreviations

AS:: OGC Abstract Specification

CRS:: coordinate reference system

GIS:: geographic information systems

GNSS:: global navigation satellite system

ISO:: International Organization for Standardisation

OGC:: Open Geospatial Consortium

UTC:: Coordinated Universal Time

////
=== accessible CRS

A CRS within which positions can be measured directly?!

[.source]
<<ogc07036>>

NOTE: Need a meaningful definition here.  Need to track this one down to its source.

[example]
The position used to calculate the spatial model is not defined in an currently accessible CRS

Geographic CRS

Projection CRS
////



