
== Terms and Definitions

////
TODO: Add missing terms 

Comments from OGC editor:

Should probably reference OGC Abstract Specification Topic 2: Referencing by coordinates (ISO 19111:2019) as a dependency for CRS related T&Ds


////

=== Terms

==== carrier

specific format used to encode a deformation model. +
Note 1 to entry: The carrier defines how the attributes of the deformation model are encoded. 

==== implementation

software that uses an encoded deformation model to calculate displacements and apply coordinate operations. +
Note 1 to entry: The implementation encodes the formulae defined in this specification or numerically equivalent formulae.

==== producer

agency compiling a deformation model for publication

////  
To be added

coseismic (editor)
slow slip event (author)
displacement (pr)
deformation (editor)
geographic CRS (editor)
coordinate operation (author) (specify PMM and transformation)
//// 

=== Abbreviations

AS:: OGC Abstract Specification

CRS:: coordinate reference system 

GNSS:: global navigation satellite system

UTC:: universal time coordinated

////
=== accessible CRS

A CRS within which positions can be measured directly?!

[.source]
<<ogc07036>>

NOTE: Need a meaningful definition here.  Need to track this one down to its source.

[example]
The position used to calculate the spatial model is not defined in an currently accessible CRS

Geographic CRS

Projection CRS
////



