[appendix,obligation="normative"]
[[annex-conformance-requirements]]
== Conformance requirements

=== Core requirements

The core requirements  defined in the table below shall be satisfied by a deformation model which is compliant with this Abstract Specification (AS).  
The attributes of entities specified in this section shall be unambiguously identified in an encoding of a deformation model.  A specific
encoding may use different names for the entities provided that the encoding specification defines how the attributes specified below are named.

[[table-conformance-requirements]]
.Conformance requirements
[options="header"]
[valign="top"]
|=== 
|Conformance class | Requirement

|req/data/metadata a|
A deformation model shall define the following metadata:
[upperalpha]
. A unique identifier for the model including its version,
. Identification of the source CRS,
. Identification of the target CRS,
. Identification of the interpolation CRS used to define the spatial function(s),
. The valid spatial extent of the model defined in terms of the interpolation CRS (<<funcmod-extents>>),
. The valid time extent of the model,
. The units of horizontal displacement,
. The units of vertical displacement, 
. The parameters used to represent horizontal and vertical uncertainty (<<funcmod-spatial-params>>),
. The default horizontal and vertical uncertainty for each element of the model  (<<funcmod-spatial-params>>).

|req/data/crs a|
[upperalpha]
. The source CRS of a deformation model shall be a CRS with horizontal and/or vertical axes.
. The target CRS of a deformation model shall be a CRS with the same axes as the source CRS.
. The interpolation CRS shall be a two dimensional CRS.

NOTE: This is implied by the use of horizontal and vertical in this specification.

|req/data/parameters a|
[upperalpha]
. A deformation model shall define displacements in the directions of the axes of the source CRS.
. The horizontal displacement units shall be a linear unit or, if the source CRS is a geographic CRS an angular unit.
. The vertical displacement units shall be a linear unit.
. A deformation model shall define uncertainty in terms of the horizontal and vertical uncertainty.
. The horizontal and vertical uncertainty units shall be a linear unit.

NOTE: What is a linear unit

|req/data/elements a| 
[upperalpha]
. A deformation model shall comprise one or more elements.
. Each element shall comprise a spatial function and a time function.

|req/data/elementMetadata a|
An element shall define the following metadata:
[upperalpha]
. The spatial extent of the spatial function defined in terms of the interpolation CRS that may be a subset of the model extent,
. The spatial interpolation method used by the spatial function,
. The parameters defined in the spatial function which is a subset or all of the displacement and uncertainty parameters defined in the model metadata.

|req/data/elementMetadataOptional a|
[upperalpha]
. (Conditional) An element may define a default the horizontal uncertainty.
. (Conditional) An element may define a vertical uncertainty.

NOTE: What is the correct way to define optional attributes that are used by other requirements (ie calculation)

|req/data/spatialFunctionGrids a| 
[upperalpha]
. The spatial function shall be defined by parameter values at the nodes of one or more regular grids defined in terms of the interpolation CRS.

|req/data/spatialFunctionGridsOrder a|
[upperalpha]
. (Conditional) If two or more grids of a spatial function overlap then the spatial function shall define a explicit or implicit heirarchy of the grids such that one grid is ranked higher than the other.

|req/data/spatialFunctionNoData a|
[upperalpha]
. (Conditional) The parameter values at the nodes of a grid may be assigned a special _no-data_ value meaning that the paramter is undefined at that node.

|req/data/timeFunction a|
[upperalpha]
. The time function of an element shall be defined by a set of one or more base time functions.

|req/data/baseTimeFunctionMetadata a|
[upperalpha]
. The type of a base time function shall be defined as  as one of: _velocity_, _step_, _ramp_, _exponential_, _logarithmic_, _acceleration_, _hyperbolicTangent_, _cyclic_

|req/data/baseTimeFunctionMetadataOptional a|
[upperalpha]
. (Conditional) The base time function may define a start epoch.
. (Conditional) The base time function may define an end epoch.
. (Conditional) The base time function may define a function reference epoch.
. (Conditional) If the base time function type is _velocity_, _acceleration_, _cyclic_ the base time function shall define a function reference epoch.
. (Conditional) If the base time function type is _step_, _exponential_, _logarithmic_, or _hyperbolicTangent_ the base time function shall define an event epoch.
. (Conditional) If the base time function type is _exponential_, _logarithmic_, or _hyperbolicTangent_ the base time function shall define a time constant in years.
. (Conditional) If the base time function type is _cyclic_ the base time function shall define a frequency in cycles per year.

|req/implementation/extents a|
[upperalpha]
. (Conditional) the deformation shall be undefined at locations outside the spatial extent of the deformation model or at a time outside the temporal extent of the model.

|req/implementation/combiningElements a| 
(Conditional) At locations within the extents of the deformation model:
[upperalpha]
. the displacement at a time and location shall calculated as the sum of the displacement calculated from the spatial function at that location multiplied by the scalar value of the 
 of time function at that time for all the elements as defined by the formulae in <<formula-elements>>,
. A software shall calculate the uncertainty at a time and location as the root sum of squares of the uncertainty defined by the spatial function at that location multiplied by the time function at that time for all the elements as defined by the formulae in <<formula-elements>>.

|req/implementation/spatialFunctionExtents a|
[upperalpha]
. (Conditional) At locations within the deformation model extents and outside the extents of an element the displacement and uncertainty of the element are zero. 

|req/implementation/spatialFunctionGrid a|
(Conditional) At a location within the deformation model extents:
[upperalpha]
. (Conditional) At a location that is within one or more of the grids of a spatial function the spatial function shall be calculated using the highest ranked of the grids which include that location,
. (Conditional) If the spatial model interpolation method is _bilinear_ then the spatial function parameters shall be calculated from the using the selected grid as defined by the formulae in <<formula-bilinear-interpolation>>,
. (Conditional) If any of the grid node values of a parameter used to calculate that parameter at a location are _no-data_, then the value of the parameter shall be undefined at that location,
. (Conditional) At a location that is not within any of the grids of a spatial model the deformation and uncertainty of the spatial model shall be zero.

|req/implementation/spatialFunctionDefaultDisplacement a| 
[upperalpha]
. (Conditional) If the spatial function parameters do not define horizontal displacement the horizontal displacement of a grid be zero.
. (Conditional) If the spatial function parameters do not define vertical displacement the vertical displacement of a grid shall be zero.

|req/implementation/spatialFunctionDefaultUncertainty a| 
[upperalpha]
. (Conditional) If the spatial function parameters do not define horizontal uncertainty, the horizontal uncertainty of a grid shall be the default horizontal uncertainty defined for the model if it is defined, or, if that is not defined, the default horizontal uncertainty for the deformation model.
. (Conditional) If the spatial function parameters do not define vertical uncertainty, the vertical uncertainty of a grid shall be the default vertical uncertainty defined for the model if it is defined, or, if that is not defined, the default vertical uncertainty for the deformation model.

|req/implementation/timeFunction a|
[upperalpha]
. (Conditional) For any time within the time extents of the deformation model, the calculated value of a time function shall be the sum of the values of its constituent base time functions at that time.

|req/implementation/baseTimeFunction a|
[upperalpha]
. (Conditional) For any time within the time extents of the deformation model, the caculated value of a base time function shall be as defined by the formulae in <<formula-time-function>>.

|req/implementation/pointMotion a|
[upperalpha]
. (Conditional) When the model is used as a point motion model to propogate a coordinate between two different epochs, the calculated of displacement between the epochs and the uncertainty of the displacement shall be as defined by the formulae in <<formula-conversion-between-epochs>>.

|req/implementation/applyDisplacement a|
[upperalpha]
. (Conditional) When a target CRS coordinate is calculated by applying a calculated displacement to a source CRS coordinate, the target CRS coordinate shall be as defined by the formulae in <<formula-apply-displacement>>.

|===
