[[annex-conformance-requirements]]
[appendix,obligation="normative"]
== Conformance requirements

The normative provisions in this Abstract Specification are denoted by the URI http://www.opengis.net/spec/deformation-model/1.0.

All requirements that appear in this Abstract Specification are denoted by partial URIs which are relative to this base URI.

[[conformance-requirements-model]]
=== Model requirements

To be conformant with this Abstract Specification a deformation model shall satisfy the requirements in <<table-conformance-requirements-model>>.  
The attributes of entities specified in the requirements shall be unambiguously identified in an encoding of a deformation model.  A specific
encoding may use different names or structure for the entities provided that the encoding specification defines how the deformation model attributes are identified.

[[table-conformance-requirements-model]]
.Data requirements
[options="header"]
[valign="top"]
|=== 
|Conformance class | Requirement

|req/model/metadata a|
A deformation model shall define the following metadata (<<funcmod-model-attributes>>):
[upperalpha]
. A unique identifier for the model including its version,
. The measure of horizontal uncertainty, e.g. "95% confidence" (<<funcmod-spatial-params>>),
. The measure of vertical uncertainty (<<funcmod-spatial-params>>),
. The _no-data_ value used to represent undefined parameter values (<<funcmod-nodata>>).

|req/model/crs a|
[upperalpha]
. A deformation model shall define a source CRS which shall be a CRS with horizontal and/or vertical axes.
. A deformation model shall define a target CRS which shall be a CRS with the same axes as the source CRS, although the order of the axes may differ.
. A deformation model shall define an interpolation CRS which shall be a two-dimensional CRS.

// NOTE: This is implied by the use of horizontal and vertical in this specification. 

|req/model/extent a|
[upperalpha]
. A deformation model shall define the valid spatial extent of the model in terms of the interpolation CRS (<<funcmod-extents>>).
. A deformation model shall specify the valid temporal extent of the model (<<funcmod-extents>>).

|req/model/elements a| 
[upperalpha]
. A deformation model shall comprise one or more elements (<<funcmod-decomposition>>).
. Each element shall comprise a spatial function and a time function (<<funcmod-decomposition>>).

|req/model/parameters a|
[upperalpha]
. A deformation model shall define displacements in the directions of the axes of the source CRS (<<funcmod-spatial-params>>).
. A deformation model shall define uncertainty in terms of horizontal and vertical uncertainty (<<funcmod-spatial-params-uncertainty>>).
. The parameters used for horizontal uncertainty that shall be one of:
* Horizontal circular uncertainty,
* East and north uncertainty e~e~, e~n~.
. Each uncertainty component of a spatial function shall be defined by one of:
* Parameters of the spatial function
* An attribute value of an element that applies for every spatial function of that element
* An attribute value of the deformation model which specifies a default value for each element which does not define the uncertainty component explicitly.
(<<funcmod-spatial-params-uncertainty>>)./
. A deformation model shall define units for each of the parameters horizontal displacement, vertical displacement, horizontal uncertainty, and vertical uncertainty that the model defines (<<funcmod-spatial-params>>).
. The units of horizontal displacement that shall be a linear unit or, if the source CRS is a geographic CRS, a linear unit or an angular unit (<<funcmod-spatial-params-displacement>>).
. The units of vertical displacement, horizontal uncertainty, and vertical uncertainty shall be a linear unit (<<funcmod-spatial-params-displacement>>).
. A deformation model shall define an uncertainty measure for each of the horizontal uncertainty and vertical uncertainty parameters that the model defines (<<funcmod-spatial-params-uncertainty>>).
. An element shall specify the parameters defined by its spatial function which shall be a subset of or all of the displacement and uncertainty parameters defined by the model (<<funcmod-spatial-params>>).

|req/model/element/spatialFunction a| 
[upperalpha]
. The spatial function shall be defined by parameter values at the nodes of one or more regular grids which defined in terms of the interpolation CRS (<<funcmod-spatial-params>>).
. An element shall define the spatial interpolation method used to calculated parameter values on its grids (<<funcmod-spatial-interpolation>>).
. An element shall specify an implicit or explicit preference between any two of its grids that overlap (<<funcmod-spatial-grids>>).
. A parameter of an element shall be assigned a _no-data_ value at a grid node at which it is not defined (<<funcmod-nodata>>).

|req/model/element/timeFunction a|
[upperalpha]
. The time function of an element shall be defined by a set of one or more base time functions (<<funcmod-time-function>>).

. A base time function shall define its type as one of: _velocity_, _acceleration_, _step_, _ramp_, _exponential_, _logBaseE_, _logBase10_, _hyperbolicTangent_, or  _cyclic_ (<<funcmod-time-function>>).

. A base time functions shall have the mandatory attributes and may have additional optional attributes as shown in <<table-time-function-attributes>>

|===

[[table-time-function-attributes]]
.Time function mandatory (M) and optional (O) attributes
[options="header"]
[valign="top"]
[cols="<,7*^"]
[headerrows=2]
|=== 
| Function type  7+| Attribute
| 
| Reference epoch footnote:tfepoch[Epochs shall be specified as a date/time or as an epoch in decimal years] 
| Start epoch footnote:tfepoch[] 
| End epoch footnote:tfepoch[] 
| Event epoch footnote:tfepoch[] 
| Time constant footnote:[A time constant shall be specified in  years] 
| Frequency footnote:[A frequency shall be specified in cycles per year] 
| Scale factor

// Type             | Ref | Sta | End | Evt | TmC | Frq | Scl 
| velocity          |  M  |  O  | O   |  -  |  -  |  -  |  O
| acceleration      |  M  |  O  | O   |  -  |  -  |  -  |  O
| step              |  M  |  O  | O   |  -  |  -  |  -  |  O
| ramp              |  O  |  M  | M   |  -  |  -  |  -  |  O
| exponential       |  O  |  O  | O   |  M  |  M  |  -  |  O
| logBaseE          |  O  |  O  | O   |  M  |  M  |  -  |  O
| logBase10         |  O  |  O  | O   |  M  |  M  |  -  |  O
| hyperbolicTangent |  O  |  O  | O   |  M  |  M  |  -  |  O
| cyclic            |  M  |  O  | O   |  -  |  -  |  M  |  O

|===

[[conformance-requirements-implementation]]
=== Implementation requirements

To be conformant with this Abstract Specification a software implementation shall satisfy the requirements of <<table-conformance-requirements-implementation>>.  Note that, as described in <<formula-general>>, this does not prescribe the specific formulas that a software should use, but does require that the calculations by the software should obtain results that are practically identical to those defined by the these formulas.

[[table-conformance-requirements-implementation]]
.Implementation requirements
[options="header"]
[valign="top"]
|=== 
|Conformance class | Requirement

|req/implementation/extents a|
[upperalpha]
. The deformation shall be undefined at locations outside the spatial extent of the deformation model (deformation model) or at a time outside the temporal extent of the model (<<formula-spatial-interpolation>>).

|req/implementation/element/spatialFunction a|
[upperalpha]
. At a location that is within one or more of the grids of a spatial function the spatial function shall be interpolated using the uniquely identified preferred grid which includes that location (<<formula-nested-grid-selection>>),
. The parameters of spatial function using a _bilinear_ interpolation method shall be interpolated on the preferred grid as defined by the formulas in <<formula-bilinear-interpolation>>,
. The spatial function shall be undefined at any location at which interpolating the function requires using a grid node parameter that has a _no-data_ value.
. The parameter values of a spatial function  shall be calculated as zero at any location that is not within any of the grids of the spatial function  and is within the extents of the deformation model (<<formula-spatial-interpolation>>).
. The horizontal displacement of a spatial function which does not include horizontal displacement grid parameters shall be zero (<<formula-nested-grid-selection>>).
. The vertical displacement of a spatial function which does not include a vertical displacement grid parameter shall be zero (<<formula-nested-grid-selection>>).
. The horizontal uncertainty of a spatial function which does not include horizontal uncertainty grid parameters shall be defined by the horizontal uncertainty attribute of its element, or, if that is not defined, by the default horizontal uncertainty attribute of the deformation model, or, if that is not defined, shall be zero (<<formula-spatial-default-values>>).
. The vertical uncertainty of a spatial function which does not include a vertical uncertainty grid parameter shall be defined by the vertical uncertainty attribute of its element, or, if that is not defined, by the default vertical uncertainty attribute of the deformation model, or, if that is not defined, shall be zero (<<formula-spatial-default-values>>).

|req/implementation/element/timeFunction a|
[upperalpha]
. The calculated value of a time function shall be the sum of the values of its constituent base time functions at that time (<<formula-time-function>>).
. The calculated value of a base time function shall be as defined by the formulas in <<formula-time-function>> for any time within the temporal extents of the deformation model.

|req/implementation/combiningElements a| 
At locations within the extents of the deformation model:
[upperalpha]
. the displacement at a time and location shall calculated as the sum, for all elements, of the displacement calculated from the spatial function at that location multiplied by the scalar value of the 
 of time function at that time, as defined by the formulas in <<formula-elements>>,
. the uncertainty at a time and location shall be calculated as the root sum of squares, for all elements, of the uncertainty defined by the spatial function at that location multiplied by the time function at that time, as defined by the formulas in <<formula-elements>>.

|req/implementation/displacement a|
[upperalpha]
. A target CRS coordinate shall be calculated by applying a calculated displacement to a source CRS coordinate as defined by the formulas in <<formula-apply-displacement>>.

|req/implementation/pointMotion a|
[upperalpha]
. The calculated of displacement and its uncertainty between two epochs shall be as defined by the formulas in <<formula-conversion-between-epochs>>.

|===
