[appendix]
:appendix-caption: Appendix
== Glossary


Displacement::

  Displacement refers to the change in the position (or location) of a point in a frame of reference as a function of time. For a body displacement refers to the sum of rigid body rotation and strain.
+
_Note:_ Displacement can arise from episodic or continuous motion.

Deformation::
  Deformation refers to the change in size, shape or other metric property of a body. If all the particles that comprise the body move without producing a change in the size or shape of the body, this is called rigid body motion. However, if the size or shape of the body changes, this is called deformation.

Strain:: 
  Strain is defined as the relative change in the position of points within a body that has undergone deformation.
+
_Note:_ Define the body in question when required.
+
_Note:_ Forces may be specified explicitly (for example, surface loads), or implicitly (for example, through an imposed slip distribution on a fault)

Deformation Model Functional Model (DMFM)::
  A Deformation Model Functional Model is a mathematical description of a Deformation Model
+
_Note:_ The DFM describes the displacement of the position of points on the surface of a body, either instantaneously or over time. The magnitude and direction of the displacement is represented as a function of time. 
+
_Note:_ Define the body in question when required.