== Definition of a Deformation Model

The definition of a deformation model adopted for this work is:
____
A deformation model is a model of the displacement of the earth’s surface within a defined spatial and temporal extent.  It predicts the location of a point fixed to the surface at an any time within the temporal extent in terms of an accessible coordinate system.  The coordinate of the point is calculated as a displacement from a time independent reference coordinate for that point.
____ 


==== Notes

* This definition characterizes a deformation model in the context of coordinate operations, specifically time dependent coordinate transformations or point motion models.  Time dependent transformations which do not involve deformation are excluded, as these are covered by rotations or 14 parameter Bursa Wolf transformations.

* The name "deformation model" is more precisely "displacement model", as it calculates displacements.  Deformation can be derived from it as the derivative of displacement with respect to position. However the term deformation model is well established and is appropriate as the model is only required in situations where there is ground deformation.
 
* “Accessible coordinate system” means a coordinate system in which locations can be measured directly, typically an ITRF coordinate system.  

* The deformation model is only defined at the surface of the earth.  It calculates horizontal and/or vertical displacement as a function of horizontal position and time, but not of vertical position.  (Geophysical models may predict deformation within the crust, but within the context of coordinate operations this has very little practical value.)

* The deformation model should define formal uncertainties of displacements calculated from the model.  It may also define the correlation between displacements calculated for different locations and times. 

* The deformation model may represent deformation from multiple sources such as plate tectonic motion, glacial isostatic adjustment, seismic and co-seismic movement as well as human activities such as fluid extraction.

* A coordinate transformation implemented by a deformation model should be spatially continuous and uniquely invertible.  This limits the accuracy with which deformation such as fault rupture or very local movements will be represented by the model.

* The definition implies a “reference” coordinate system realised by the coordinates of points when the displacements are zero.  Commonly this is defined as the location of a point in a accessible coordinate system at a specific epoch (eg ITRF2014 at epoch 2020.0).  This is not accessible, except at that epoch.

* The deformation model must be accompanied by sufficient metadata to assess its appropriateness for use in a particular application.  This could include attributes such the authority and history of the model, the spatial and temporal extents it defines and the magnitude and dimension of the predicted displacements.  


=== Deformation Model Functional Model definition 

The deformation model functional model (DMFM) is the set of data, metadata, and algorithms required to understand and apply a deformation model, independently of any specific encoding or model format.
