== Introduction

This report proposes a definition of a functional model for deformation models used in the 
context of time dependent coordinate transformation operations.  This model has been  developed with a view to 
establishing a standard for the deformation model functional model and/or formats.

It is compiled by a project team convened by the OGC CRS DWG (Coordinate Reference System Domain Working Group).  The purpose of this team is to define the functional model(s), methods and workflows for computing coordinate offsets resulting from seismic and certain geodynamic and anthropogenic processes.   The work involves close collaboration with the CRS DWG project team developing the "Gridded Geodetic Exchange Format (GGXF)" and with IAG (International Association of Geodesy) WG 1.3.1 on "Time-dependent transformations between reference frames in deforming regions".

The motivation for this work is to support unambiguous and timely communication of deformation models from producers, typically national geodetic agencies, to the geospatial and positioning communities that require them.  
This is becoming increasingly critical as both our dependence on global positioning systems and our requirements for accurate positioning increase.

The terms of reference for this project team proposes the following steps for this work. 

* Defining the term "deformation functional model" (DFM);
* Establishing the use case(s) of a DFM;
* Defining the user needs for a DFM;
* Evaluating existing deformation functional models and methods;
* Designing a DFM fit for its intended purpose as defined by the project team; 
* Ensure the DFM addresses model uncertainty and model validity;
* Develop a strategy for promulgating the model as a standard for the geodetic community.
* Develop an encoding structure for the functional model (when grid, refer to GGXF).


